// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../components/header";

import MainFooter from "../../components/MainFooter"; // Import MainFooter

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      

        {/* Fixed header */}
        <div className="fixed top-0 left-0 w-full z-[9999] pointer-events-auto">
          <Header />
        </div>

        {/* Main content container */}
        <div className="pt-16 relative min-h-screen" data-scroll-container>
          {children}
          
          {/* Footer added to layout */}
          <MainFooter />
        </div>
      </body>
    </html>
  );
}
